export const CHANGE_MARKER_POSITION = 'CHANGE_MARKER_POSITION';
export const CHANGE_CURRENT_FLAG_INDEX = 'CHANGE_CURRENT_FLAG_INDEX';
export const ADD_FLAG_TO_SHOWN_FLAGS = 'ADD_FLAG_TO_SHOWN_FLAGS';
export const COUNT_CORRECT_ANSWER = 'COUNT_CORRECT_ANSWER';
export const CHANGE_REQUEST_STATUS = 'CHANGE_REQUEST_STATUS';
export const CHANGE_PREVIOUS_COUNTRY_CORRECT = 'CHANGE_PREVIOUS_COUNTRY_CORRECT';
export const CHANGE_PREVIOUS_COUNTRY_GIVEN = 'CHANGE_PREVIOUS_COUNTRY_GIVEN';
export const CHANGE_GAME_STATUS = 'CHANGE_GAME_STATUS';

export const HANDLE_ERROR = 'HANDLE_ERROR';